default:
  log_level: "DEBUG"
  tokens: !expr Sys.getenv("SECRET_TOKENS")
  allow_empty_tokens: true
  storage_method:
    # # SQLite backend
    # driver: "sqlite"
    # params:
    #   db_path: !expr file.path(here::here(), "telemetry.sqlite")
    #
    # # Logfile backend
    driver: "logfile"
    params:
      log_file_path: "user_stats.txt"
      session_file_path: "session_details.txt"

rsconnect:
  log_level: "DEBUG"
  allow_empty_tokens: false

production:
  log_level: "INFO"
  allow_empty_tokens: false
