default:
  log_level: DEBUG
  tokens: !expr Sys.getenv("SECRET_TOKENS")
  allow_empty_tokens: true
  storage_method:
    # SQLite backend
    # driver: sqlite
    # sqlite:
    #   params:
    #     db_path: !expr file.path(here::here(), "telemetry.sqlite")

    # Logfile backend
    driver: "logfile"
    logfile:
      params:
        log_file_path: "user_stats.txt"

test:
  log_level: FATAL
  storage_method:
    driver: sqlite
    sqlite:
      params:
        db_path: !expr ifelse(Sys.getenv("FORCE_SQLITE_AND_PATH") == "", tempfile(pattern = "user_stats", fileext = ".txt"), Sys.getenv("FORCE_SQLITE_AND_PATH"))

rsconnect:
  log_level: DEBUG
  allow_empty_tokens: false

production:
  log_level: INFO
  allow_empty_tokens: false
