# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "2272e4f5-c7cc-45d0-9400-31a5f1c81e4d"
      MARIADB_PASSWORD: mysecretpassword
      MARIADB_USER: mariadb
      MARIADB_DATABASE: shiny_telemetry
    ports:
      - 3306:3306
