on: [push, pull_request]

name: R-CMD-check

jobs:
  ###################
  # R CMD check job #
  ###################
  r-cmd:
    name: R CMD Check ${{ matrix.config.os }} (${{ matrix.config.r }})

    runs-on: ${{ matrix.config.os }}

    timeout-minutes: 30

    #############################
    # Run on multiple platforms #
    #############################
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'oldrel'}

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout repository
        uses: actions/checkout@v3

      #############
      # Install R #
      #############
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      ##########################
      # Install R Dependencies #
      ##########################
      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # Necessary to avoid object usage linter errors.
          extra-packages: local::.

      ###########################
      # Perform the R CMD check #
      ###########################
      - name: R CMD check
        if: always()
        uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"note"'

  ##############
  # Linter job #
  ##############
  linter:
    name: SuperLinter 🦸‍♀️

    runs-on: ubuntu-latest

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
