---
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: URL checker

jobs:
  ###################
  # R CMD check job #
  ###################
  urls:
    name: URL checker

    runs-on: ubuntu-latest

    timeout-minutes: 30

    #############################
    # Run on multiple platforms #
    #############################
    steps:
      - name: Checkout repository
        ##########################
        # Checkout the code base #
        ##########################
        uses: actions/checkout@v3

      - name: Install R
        #############
        # Install R #
        #############
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - name: Install R package dependencies
        ##########################
        # Install R Dependencies #
        ##########################
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # Necessary to avoid object usage linter errors.
          extra-packages: |
            any::urlchecker

      - name: Check URLs with urlchecker 🔬
        run: |
          # For unexplained reasons, parallel = FALSE is required to prevent some false positives.
          bad_urls <- nrow(print(urlchecker::url_check(".", parallel = FALSE)))
          if (bad_urls > 0) {
            stop("Looks like a total of ", bad_urls, " URL(s) were found! Please correct them.")
          }
        shell: Rscript {0}
